export const R = {
  auth: {
    register: "/auth/register",
    login: "/auth/login",
    refresh: "/auth/refresh",
    logout: "/auth/logout",
    verifyEmail: "/auth/verify-email",
    resendVerification: "/auth/resend-verification",
    forgotPassword: "/auth/forgot-password",
    resetPassword: "/auth/reset-password",
    me: "/auth/me",
    mePatch: "/auth/me",
    changePassword: "/auth/me/password",
    pushToken: "/auth/me/push-token",
  },
  usuarios: { list: "/usuarios", byId: (id:number)=>`/usuarios/${id}` },
  uploads: { presign: "/uploads/presign", direct: "/uploads", delete: (id:string|number)=>`/uploads/${id}` },
  complejos: {
    list: "/complejos", create: "/complejos",
    byId: (id:number)=>`/complejos/${id}`,
    canchas: (id:number)=>`/complejos/${id}/canchas`,
    horarios: (id:number)=>`/complejos/${id}/horarios`,
    bloqueos: (id:number)=>`/complejos/${id}/bloqueos`,
    resumen: (id:number)=>`/complejos/${id}/resumen`,
  },
  canchas: {
    list: "/canchas", create: "/canchas",
    byId: (id:number)=>`/canchas/${id}`,
    fotos: (id:number)=>`/canchas/${id}/fotos`,
    fotoDel: (id:number,mid:number|string)=>`/canchas/${id}/fotos/${mid}`,
  },
  disponibilidad: {
    slots: "/disponibilidad",
    bloqueos: "/bloqueos",
    bloqueoDel: (id:number)=>`/bloqueos/${id}`,
    horarios: "/horarios",
    horarioPatch: (id:number)=>`/horarios/${id}`,
    horarioDel: (id:number)=>`/horarios/${id}`,
  },
  pricing: { reglas: "/pricing/reglas", reglaById: (id:number)=>`/pricing/reglas/${id}` },
  promos: { list: "/promociones", byId:(id:number)=>`/promociones/${id}`, validar:"/promociones/validar" },
  search: { nearby:"/search/nearby", sugerencias:"/search/sugerencias", slots:"/search/slots" },
  reservas: {
    adminList:"/reservas", mias:"/reservas/mias", cotizar:"/reservas/cotizar", create:"/reservas",
    byId:(id:number)=>`/reservas/${id}`, patch:(id:number)=>`/reservas/${id}`,
    cancelar:(id:number)=>`/reservas/${id}/cancelar`,
    confirmar:(id:number)=>`/reservas/${id}/confirmar`,
    checkIn:(id:number)=>`/reservas/${id}/check-in`,
    noShow:(id:number)=>`/reservas/${id}/no-show`,
  },
  pagos: {
    crearIntencion:"/pagos/crear-intencion",
    byId:(id:number)=>`/pagos/${id}`,
    reembolsar:(id:number)=>`/pagos/${id}/reembolsar`,
  },
  resenas: {
    list:"/resenas", create:"/resenas", byId:(id:number)=>`/resenas/${id}`,
    reportar:(id:number)=>`/resenas/${id}/reportar`,
  },
  favoritos: { list:"/favoritos", add:(id:number)=>`/favoritos/${id}`, del:(id:number)=>`/favoritos/${id}` },
  notifs: {
    list:"/notificaciones",
    leer:(id:number|string)=>`/notificaciones/${id}/leer`,
    prefs:"/preferencias/notifications",
  },
  denuncias: {
    list:"/denuncias", create:"/denuncias", byId:(id:number)=>`/denuncias/${id}`,
    resolver:(id:number)=>`/denuncias/${id}/resolver`,
  },
  grupos: {
    list:"/grupos", create:"/grupos", byId:(id:number)=>`/grupos/${id}`,
    unirme:(id:number)=>`/grupos/${id}/unirme`,
    salir:(id:number)=>`/grupos/${id}/salir`,
    miembros:(id:number)=>`/grupos/${id}/miembros`,
    expulsar:(id:number,uid:number)=>`/grupos/${id}/miembros/${uid}/expulsar`,
  },
  eventos: {
    list:"/eventos", create:"/eventos", byId:(id:number)=>`/eventos/${id}`,
    unirme:(id:number)=>`/eventos/${id}/unirme`,
    salir:(id:number)=>`/eventos/${id}/salir`,
    participantes:(id:number)=>`/eventos/${id}/participantes`,
  },
  mis: { complejos:"/mis/complejos", canchas:"/mis/canchas", reservas:"/mis/reservas", stats:"/mis/estadisticas" },
  admin: {
    usuarios:"/admin/usuarios",
    usuarioRol:(id:number)=>`/admin/usuarios/${id}/rol`,
    usuarioBloqueo:(id:number)=>`/admin/usuarios/${id}/bloquear`,
    resenasModeracion:"/admin/resenas/moderacion",
    resenaOcultar:(id:number)=>`/admin/resenas/${id}/ocultar`,
    denuncias:"/admin/denuncias",
    pagoForzar:(id:number)=>`/admin/pagos/${id}/forzar-confirmacion`,
    auditoria:"/admin/auditoria",
  },
  superadmin: { params:"/superadmin/parametros", stats:"/superadmin/estadisticas", salud:"/superadmin/salud" },
  utils: { reverse:"/utils/geo/reverse", ics:"/utils/export/ics", timezones:"/utils/timezones", ping:"/utils/ping" },
};
